# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for all branches
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called test
  test:
    name: Test on Python ${{ matrix.python-version }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9']
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v2
      
      # Action provided by conda-incubator to setup conda env, doesn't activate the base environment
      # but 'project' environment
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: project
          environment-file: environment.yml
          
      
      # Default action: run the tests
      - name: Run tests
        shell: bash
        run: |
          conda info -a
          pytest test_database.py
